imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: notice
            handler:      grouped
            excluded_404s:
                - ^/
        grouped:
            type:    group
            members: [streamed, buffered]
        streamed:
            type:  rotating_file
            path:  "%kernel.logs_dir%/%kernel.environment%/%kernel.environment%.log"
            level: debug
        buffered:
            type:    buffer
            handler: swift
        swift:
            type:       swift_mailer
            from_email: %mailer_user%
            to_email:   %mailer_user%
            subject:    %mailer_prefix_site%An Error Occurred
            level:      debug
assetic:
    use_controller: true

#swiftmailer:
#    delivery_address: me@example.com
