imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

doctrine:
    orm:
        metadata_cache_driver:
            type: service
            id: doctrine.cache.memcached
        query_cache_driver:
            type: service
            id: doctrine.cache.memcached
        result_cache_driver:
            type: service
            id: doctrine.cache.memcached

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: notice
            handler:      grouped
        grouped:
            type:    group
            members: [streamed, console, buffered]
        streamed:
            type:  rotating_file
            path:  "%kernel.logs_dir%/%kernel.environment%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
        buffered:
            type:    buffer
            handler: swift
        swift:
            type:       swift_mailer
            from_email: %mailer_user%
            to_email:   %mailer_user%
            subject:    %mailer_prefix_site%An Error Occurred
            level:      debug
